# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_status',
            field=models.CharField(choices=[('d', '丢弃'), ('p', '发布'), ('w', '草稿')], default=django.utils.timezone.now, max_length=1, verbose_name='状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=True, verbose_name='内容'),
        ),
    ]
